name: Run Tests and Coverage Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 可以根据需要修改版本

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run coverage and generate report
        run: |
          coverage run -m pytest
          coverage report -m
          coverage html

      - name: Upload HTML coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov-report
          path: htmlcov/

